# BoardConfig.mk - Infinix Smart 5 (X657B)

BOARD_VENDOR := infinix
TARGET_BOARD_PLATFORM := mt6761
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# Kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel/zImage

# Ramdisk
BOARD_RAMDISK_USE_LZMA := true

# Recovery
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_FLASH_BLOCK_SIZE := 131072

# AVB / vbmeta
BOARD_AVB_ENABLE := true
TARGET_PREBUILT_VBMETAIMAGE := $(DEVICE_PATH)/prebuilt/vbmeta.img
