name: Build TWRP Infinix X657B

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout device tree
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3

      - name: Setup repo tool
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=~/bin:$PATH" >> $GITHUB_ENV

      - name: Init minimal AOSP tree
        run: |
          mkdir -p ~/android/twrp
          cd ~/android/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Copy device tree
        run: |
          cd ~/android/twrp/device
          mkdir -p infinix
          cp -r $GITHUB_WORKSPACE infinix/Infinix-X657B

      - name: Lunch & build
        run: |
          cd ~/android/twrp
          . build/envsetup.sh
          lunch twrp_x657b-eng
          mka recoveryimage -j$(nproc)

      - name: Upload TWRP image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-x657b
          path: out/target/product/x657b/recovery.img
